const express = require('express')
const http = require('http')
const { Server: SocketIOServer } = require('socket.io')
const next = require('next')
const cors = require('cors') // Import the cors package

// Initialize Next.js app
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

// Create an Express application
const server = express()
const httpServer = http.createServer(server)
const io = new SocketIOServer(httpServer, {
    cors: {
        origin: '*', // Allow all origins or specify the allowed origins
        methods: ['GET', 'POST'],
    },
})

// Use CORS middleware
server.use(cors())

const symbols = [
    '3M India Ltd.',
    'ABB India Ltd.',
    'ACC Ltd.',
    'Aarti Drugs Ltd.',
    'Aarti Industries Ltd.',
    'Aavas Financiers Ltd.',
    'Abbott India Ltd.',
    'Adani Enterprises Ltd.',
    'Adani Green Energy Ltd.',
    'Adani Ports and Special Economic Zone Ltd.',
    'Adani Total Gas Ltd.',
    'Adani Transmission Ltd.',
    'Aditya Birla Capital Ltd.',
    'Aditya Birla Fashion and Retail Ltd.',
    'Advanced Enzyme Technologies Ltd.',
    'Aegis Logistics Ltd.',
    'Affle (India) Ltd.',
    'Ajanta Pharma Ltd.',
    'Alembic Pharmaceuticals Ltd.',
    'Alkyl Amines Chemicals Ltd.',
    'Alkem Laboratories Ltd.',
    'Allcargo Logistics Ltd.',
    'Apollo Hospitals Enterprise Ltd.',
    'Apollo Tyres Ltd.',
    'Apl Apollo Tubes Ltd.',
    'Aptus Value Housing Finance India Ltd.',
    'Arihant Capital Markets Ltd.',
    'Ashok Leyland Ltd.',
    'Asi Industries Ltd.',
    'Asian Paints Ltd.',
    'Aster DM Healthcare Ltd.',
    'Astrazeneca Pharma India Ltd.',
    'Astral Ltd.',
    'Atul Ltd.',
    'AU Small Finance Bank Ltd.',
    'Avanti Feeds Ltd.',
    'Avenue Supermarts Ltd.',
    'Axis Bank Ltd.',
    'B P C L Ltd.',
    'Bajaj Auto Ltd.',
    'Bajaj Consumer Care Ltd.',
    'Bajaj Electricals Ltd.',
    'Bajaj Finance Ltd.',
    'Bajaj Finserv Ltd.',
    'Bajaj Holdings and Investment Ltd.',
    'Balkrishna Industries Ltd.',
    'Balrampur Chini Mills Ltd.',
    'Bandhan Bank Ltd.',
    'Bank Of Baroda Ltd.',
    'Bank Of India Ltd.',
    'Bank Of Maharashtra Ltd.',
    'Bata India Ltd.',
    'Bayer Cropscience Ltd.',
    'B C R I L Ltd.',
    'Berger Paints India Ltd.',
    'Bharat Dynamics Ltd.',
    'Bharat Electronics Ltd.',
    'Bharat Forge Ltd.',
    'Bharat Heavy Electricals Ltd.',
    'Bharat Petroleum Corporation Ltd.',
    'Bharti Airtel Ltd.',
    'Biocon Ltd.',
    'Birlasoft Ltd.',
    'Bliss GVS Pharma Ltd.',
    'Blue Dart Express Ltd.',
    'Blue Star Ltd.',
    'B L S Ltd.',
    'Bombay Burmah Trading Corporation Ltd.',
    'Bosch Ltd.',
    'B P N T Ltd.',
    'Brigade Enterprises Ltd.',
    'Britannia Industries Ltd.',
    'B R N G Ltd.',
    'Can Fin Homes Ltd.',
    'Canara Bank Ltd.',
    'Caplin Point Laboratories Ltd.',
    'Capri Global Capital Ltd.',
    'Castrol India Ltd.',
    'C E S C Ltd.',
    'C G Power and Industrial Solutions Ltd.',
    'Chemcon Speciality Chemicals Ltd.',
    'Chennai Petroleum Corporation Ltd.',
    'Cholamandalam Financial Holdings Ltd.',
    'Cholamandalam Investment and Finance Company Ltd.',
    'Cipla Ltd.',
    'City Union Bank Ltd.',
    'C L E I A Ltd.',
    'Coal India Ltd.',
    'Cochin Shipyard Ltd.',
    'Colgate-Palmolive (India) Ltd.',
    'Container Corporation Of India Ltd.',
    'Coromandel International Ltd.',
    'CreditAccess Grameen Ltd.',
    'Crompton Greaves Consumer Electricals Ltd.',
    'CSB Bank Ltd.',
    'C T M L Ltd.',
    'Cummins India Ltd.',
    'C T E Ltd.',
    'Dabur India Ltd.',
    'Dalmia Bharat Ltd.',
    'DB Corp Ltd.',
    'D C B Bank Ltd.',
    'Deepak Fertilisers And Petrochemicals Corporation Ltd.',
    'Deepak Nitrite Ltd.',
    'Delhivery Ltd.',
    'Delta Corp Ltd.',
    'Dhanuka Agritech Ltd.',
    'Dishman Carbogen Amcis Ltd.',
    "Divi's Laboratories Ltd.",
    'Dixon Technologies (India) Ltd.',
    'D L F Ltd.',
    'Dodla Dairy Ltd.',
    'Dr. Lal Pathlabs Ltd.',
    "Dr. Reddy's Laboratories Ltd.",
    'E I D Parry (India) Ltd.',
    'Edelweiss Financial Services Ltd.',
    'Eicher Motors Ltd.',
    'Elgi Equipments Ltd.',
    'Emami Ltd.',
    'Endurance Technologies Ltd.',
    'Engineers India Ltd.',
    'Eris Lifesciences Ltd.',
    'Escorts Ltd.',
    'Ester Industries Ltd.',
    'Exide Industries Ltd.',
    'F A P B Ltd.',
    'F A B I L Ltd.',
    'F M C T Ltd.',
    'F M L Ltd.',
    'F B L Ltd.',
    'Fine Organic Industries Ltd.',
    'Finolex Cables Ltd.',
    'Finolex Industries Ltd.',
    'Firstsource Solutions Ltd.',
    'F A C S Ltd.',
    'Fortis Healthcare Ltd.',
    'F A M Ltd.',
    'Future Retail Ltd.',
    'G N F C Ltd.',
    'GAIL (India) Ltd.',
    'Ganesha Ecosphere Ltd.',
    'Gateway Distriparks Ltd.',
    'Geojit Financial Services Ltd.',
    'Gillette India Ltd.',
    'Glenmark Pharmaceuticals Ltd.',
    'GMM Pfaudler Ltd.',
    'G N L T Ltd.',
    'Godfrey Phillips India Ltd.',
    'Godrej Agrovet Ltd.',
    'Godrej Consumer Products Ltd.',
    'Godrej Industries Ltd.',
    'Godrej Properties Ltd.',
    'Gokaldas Exports Ltd.',
    'Granules India Ltd.',
    'Graphite India Ltd.',
    'Greaves Cotton Ltd.',
    'Greenlam Industries Ltd.',
    'Grindwell Norton Ltd.',
    'Grindwell W L Ltd.',
    'Grasim Industries Ltd.',
    'Gravita India Ltd.',
    'Gujarat Alkalies and Chemicals Ltd.',
    'Gujarat Fluorochemicals Ltd.',
    'Gujarat Gas Ltd.',
    'Gujarat State Fertilizers & Chemicals Ltd.',
    'Gujarat State Petronet Ltd.',
    'Gulf Oil Lubricants India Ltd.',
    'Happiest Minds Technologies Ltd.',
    'H G I Ltd.',
    'HDFC Asset Management Company Ltd.',
    'HDFC Bank Ltd.',
    'HDFC Life Insurance Company Ltd.',
    'Hindalco Industries Ltd.',
    'Hindustan Aeronautics Ltd.',
    'Hindustan Copper Ltd.',
    'Hindustan Petroleum Corporation Ltd.',
    'Hindustan Unilever Ltd.',
    'Hinduja Global Solutions Ltd.',
    'Hindustan Zinc Ltd.',
    'Hindware Home Innovation Ltd.',
    'Honeywell Automation India Ltd.',
    'H P C L Ltd.',
    'Housing Development Finance Corporation Ltd.',
    'Hudco Ltd.',
    'I D F C First Bank Ltd.',
    'I C I Ltd.',
    'I I S Ltd.',
    'I I P Ltd.',
    'I I Ltd.',
    'I T C Ltd.',
    'ICICI Bank Ltd.',
    'ICICI Lombard General Insurance Company Ltd.',
    'ICICI Prudential Life Insurance Company Ltd.',
    'ICRA Ltd.',
    'IDBI Bank Ltd.',
    'IDFC Ltd.',
    'IIFL Finance Ltd.',
    'Indiamart Intermesh Ltd.',
    'Indian Bank Ltd.',
    'Indian Energy Exchange Ltd.',
    'Indian Hotels Company Ltd.',
    'Indian Oil Corporation Ltd.',
    'Indiabulls Housing Finance Ltd.',
    'Indiabulls Real Estate Ltd.',
    'Indigo Paints Ltd.',
    'Indoco Remedies Ltd.',
    'IndusInd Bank Ltd.',
    'Info Edge (India) Ltd.',
    'Infosys Ltd.',
    'Ingersoll-Rand (India) Ltd.',
    'INOX Leisure Ltd.',
    'InterGlobe Aviation Ltd.',
    'Intellect Design Arena Ltd.',
    'IPCA Laboratories Ltd.',
    'ITD Cementation India Ltd.',
    'ITI Ltd.',
    'J B C Ltd.',
    'J M F Ltd.',
    'Jubilant FoodWorks Ltd.',
    'Jubilant Ingrevia Ltd.',
    'Jubilant Pharmova Ltd.',
    'Jyothy Labs Ltd.',
    'K R R Ltd.',
    'K S B Ltd.',
    'Kalpataru Power Transmission Ltd.',
    'Kansai Nerolac Paints Ltd.',
    'Karur Vysya Bank Ltd.',
    'KEI Industries Ltd.',
    'Kotak Mahindra Bank Ltd.',
    'K P I T Technologies Ltd.',
    'K P R Mill Ltd.',
    'Krishna Institute of Medical Sciences Ltd.',
    'K S P Ltd.',
    'L T D Ltd.',
    'Lakshmi Machine Works Ltd.',
    'Laurus Labs Ltd.',
    'Lemon Tree Hotels Ltd.',
    'L G B R Ltd.',
    'Linde India Ltd.',
    'LIC Housing Finance Ltd.',
    'Lupin Ltd.',
    'Lux Industries Ltd.',
    'Mahanagar Gas Ltd.',
    'Mahindra & Mahindra Ltd.',
    'Mahindra & Mahindra Financial Services Ltd.',
    'Mahindra Holidays & Resorts India Ltd.',
    'Mahindra Lifespace Developers Ltd.',
    'Manappuram Finance Ltd.',
    'Marico Ltd.',
    'Maruti Suzuki India Ltd.',
    'MAS Financial Services Ltd.',
    'Max Financial Services Ltd.',
    'Max Healthcare Institute Ltd.',
    'Mayur Uniquoters Ltd.',
    'Mazagon Dock Shipbuilders Ltd.',
    'M T A E Ltd.',
    'Metropolis Healthcare Ltd.',
    'Mindtree Ltd.',
    'Mishra Dhatu Nigam Ltd.',
    'MMTC Ltd.',
    'Motherson Sumi Systems Ltd.',
    'Motilal Oswal Financial Services Ltd.',
    'Mphasis Ltd.',
    'M R C Ltd.',
    'Multi Commodity Exchange of India Ltd.',
    'Muthoot Finance Ltd.',
    'Natco Pharma Ltd.',
    'N A E L Ltd.',
    'Navin Fluorine International Ltd.',
    'Nazara Technologies Ltd.',
    'NBCC (India) Ltd.',
    'Nestle India Ltd.',
    'Nesco Ltd.',
    'N I L Ltd.',
    'N L A Ltd.',
    'Nippon Life India Asset Management Ltd.',
    'Nocil Ltd.',
    'NRB Bearings Ltd.',
    'Nuvoco Vistas Corporation Ltd.',
    'Oberoi Realty Ltd.',
    'Oil & Natural Gas Corporation Ltd.',
    'Oil India Ltd.',
    'Omaxe Ltd.',
    'One 97 Communications Ltd.',
    'Oracle Financial Services Software Ltd.',
    'Orient Electric Ltd.',
    'Orient Refractories Ltd.',
    'Oriental Hotels Ltd.',
    'Page Industries Ltd.',
    'Parag Milk Foods Ltd.',
    'PCBL Ltd.',
    'Persistent Systems Ltd.',
    'Petronet LNG Ltd.',
    'Pfizer Ltd.',
    'PI Industries Ltd.',
    'Pidilite Industries Ltd.',
    'PI Industries Ltd.',
    'Polycab India Ltd.',
    'Power Finance Corporation Ltd.',
    'Power Grid Corporation of India Ltd.',
    'Praj Industries Ltd.',
    'Prestige Estates Projects Ltd.',
    'Procter & Gamble Hygiene and Health Care Ltd.',
    'PSP Projects Ltd.',
    'PTC India Ltd.',
    'Punjab National Bank Ltd.',
    'Quess Corp Ltd.',
    'R R C Ltd.',
    'R R H L Ltd.',
    'Rail Vikas Nigam Ltd.',
    'Rain Industries Ltd.',
    'Rajesh Exports Ltd.',
    'Rallis India Ltd.',
    'Rane Holdings Ltd.',
    'RattanIndia Enterprises Ltd.',
    'RBL Bank Ltd.',
    'REC Ltd.',
    'Redington (India) Ltd.',
    'Relaxo Footwears Ltd.',
    'Reliance Industries Ltd.',
    'Route Mobile Ltd.',
    'Ruchi Soya Industries Ltd.',
    'S A I L Ltd.',
    'S B I Cards and Payment Services Ltd.',
    'S B I Life Insurance Company Ltd.',
    'S Chand And Company Ltd.',
    'S H K L Ltd.',
    'S P L Ltd.',
    'Sanofi India Ltd.',
    'Sapphire Foods India Ltd.',
    'Sasken Technologies Ltd.',
    'Saurashtra Cement Ltd.',
    'Schaeffler India Ltd.',
    'S H B L Ltd.',
    'Security and Intelligence Services (India) Ltd.',
    'Shoppers Stop Ltd.',
    'Shriram City Union Finance Ltd.',
    'Shriram Transport Finance Company Ltd.',
    'Siemens Ltd.',
    'SIS Ltd.',
    'SKF India Ltd.',
    'Solara Active Pharma Sciences Ltd.',
    'Solar Industries India Ltd.',
    'Sona BLW Precision Forgings Ltd.',
    'Sonata Software Ltd.',
    'S P I L Ltd.',
    'Sobha Ltd.',
    'Solar Pharmaceuticals Ltd.',
    'SpiceJet Ltd.',
    'Sterlite Technologies Ltd.',
    'S P P E Ltd.',
    'Star Cement Ltd.',
    'Star Health and Allied Insurance Company Ltd.',
    'State Bank Of India Ltd.',
    'Steel Authority Of India Ltd.',
    'Sterling and Wilson Renewable Energy Ltd.',
    'Strides Pharma Science Ltd.',
    'Sudarshan Chemical Industries Ltd.',
    'Sunteck Realty Ltd.',
    'Sun TV Network Ltd.',
    'Sun Pharmaceutical Industries Ltd.',
    'Sundaram Clayton Ltd.',
    'Sundaram Finance Ltd.',
    'Sundram Fasteners Ltd.',
    'Supreme Industries Ltd.',
    'Suven Pharmaceuticals Ltd.',
    'Suven Life Sciences Ltd.',
    'Swan Energy Ltd.',
    'Symphony Ltd.',
    'Synthite Industries Ltd.',
    'T V Today Network Ltd.',
    'Tata Chemicals Ltd.',
    'Tata Communications Ltd.',
    'Tata Consumer Products Ltd.',
    'Tata Consultancy Services Ltd.',
    'Tata Elxsi Ltd.',
    'Tata Investment Corporation Ltd.',
    'Tata Motors Ltd.',
    'Tata Power Company Ltd.',
    'Tata Steel Ltd.',
    'Teamlease Services Ltd.',
    'Tech Mahindra Ltd.',
    'Thangamayil Jewellery Ltd.',
    'The India Cements Ltd.',
    'The Indian Hotels Company Ltd.',
    'The Karnataka Bank Ltd.',
    'The New India Assurance Company Ltd.',
    'The Ramco Cements Ltd.',
    'Thermax Ltd.',
    'Thomas Cook (India) Ltd.',
    'Thyrocare Technologies Ltd.',
    'Titan Company Ltd.',
    'Torrent Pharmaceuticals Ltd.',
    'Torrent Power Ltd.',
    'Trent Ltd.',
    'Triveni Turbine Ltd.',
    'TTK Prestige Ltd.',
    'Tube Investments of India Ltd.',
    'T V S Motor Company Ltd.',
    'U B Ltd.',
    'U F L Ltd.',
    'U I T S Ltd.',
    'UltraTech Cement Ltd.',
    'Uni Abex Alloy Products Ltd.',
    'Unichem Laboratories Ltd.',
    'Union Bank Of India Ltd.',
    'United Breweries Ltd.',
    'United Spirits Ltd.',
    'Usha Martin Ltd.',
    'V A T Ltd.',
    'Vaibhav Global Ltd.',
    'Vardhman Textiles Ltd.',
    'Varun Beverages Ltd.',
    'Vedanta Ltd.',
    "Venky's (India) Ltd.",
    'Veranda Learning Solutions Ltd.',
    'V-Guard Industries Ltd.',
    'Vijaya Diagnostic Centre Ltd.',
    'V I P Industries Ltd.',
    'Vodafone Idea Ltd.',
    'Voltamp Transformers Ltd.',
    'Voltas Ltd.',
    'V-Guard Industries Ltd.',
    'W S L Ltd.',
    'W P I Ltd.',
    'W S L Ltd.',
    'WABCO India Ltd.',
    'Wipro Ltd.',
    'Wockhardt Ltd.',
    'Yes Bank Ltd.',
    'Zensar Technologies Ltd.',
    'Zee Entertainment Enterprises Ltd.',
    'Zydus Wellness Ltd.',
]

const stockData = symbols.reduce((acc, symbol) => {
    const open = parseFloat((Math.random() * 1000).toFixed(2))
    const price = open
    const percentChange = '0'

    acc[symbol] = {
        symbol,
        price,
        percentChange,
    }
    return acc
}, {})

const updateStockData = () => {
    Object.keys(stockData).forEach((symbol) => {
        const data = stockData[symbol]
        const change = parseFloat((Math.random() * 2 - 1).toFixed(2)) // Between -1 and +1
        const newPrice = parseFloat((data.price + change).toFixed(2))

        if (newPrice > 0) {
            data.price = newPrice
            const previousPrice = data.price - change
            data.percentChange = (
                ((data.price - previousPrice) / previousPrice) *
                100
            ).toFixed(2)
        }
    })
}

io.on('connection', (socket) => {
    console.log('ticker-tape server connected')
    socket.emit('stockData', stockData)

    const interval = setInterval(() => {
        updateStockData()
        socket.emit('stockData', stockData)
    }, 1000)

    socket.on('disconnect', () => {
        console.log('Client disconnected')
        clearInterval(interval)
    })
})

server.get('/api/stocks', (req, res) => {
    res.json(stockData)
})

server.get('/api/stocks/:symbol', (req, res) => {
    const symbol = decodeURIComponent(req.params.symbol)
    const data = stockData[symbol]
    if (data) {
        res.json(data)
    } else {
        res.status(404).json({ error: 'Stock symbol not found' })
    }
})
// New endpoint to search for stock symbols
server.get('/api/search', (req, res) => {
    const query = req.query.q ? req.query.q.toLowerCase() : ''
    if (!query) {
        // If no query is provided, return an empty list or all symbols
        return res.json([])
    }

    const results = symbols.filter((symbol) =>
        symbol.toLowerCase().startsWith(query)
    )
    res.json(results)
})
server.all('*', (req, res) => {
    return handle(req, res)
})

const PORT = process.env.PORT || 4001
httpServer.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`)
})
