import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Inter } from 'next/font/google'
import AdminLayout from '@/components/admin-dashboard/AdminLayout'
import UserLayout from '@/components/user-layout/UserLayout'

import styles from './temporary.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // Fetch the session server-side using your auth configuration
    const session = await auth()

    const role = session?.user?.role || null

    // Determine which layout to use based on the role
    const Layout = role === 'ADMIN' ? AdminLayout : UserLayout

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                    <Layout>
                        <div className={styles.childrenContainer}>
                            <div className={styles.childrenContent}>
                                {children}
                            </div>
                        </div>
                    </Layout>
                </SessionProvider>
            </body>
        </html>
    )
}
